### PR TITLE
Handle unexpected title formats.

### PR DESCRIPTION
**Pull request by kwadkore**
Fail gracefully if the title line is not in the expected format instead of exiting due to an index out of range runtime error.

### CODE REVIEW

**Comment by Akenaide** [comment]
Sure, good idea. May I know where this happen ?

**Comment by kwadkore** [comment]
I just ran the script and it kept crashing. The test contains the title
that was causing the failure.

**Comment by Akenaide** [comment]
Yeah, I saw the title, but the other information had no relation to it. The title was about Fantasia, while the info was actually about Love Live! So, I thought it was a fabrication.
Can you change it please ? Here the url: [https://ws-tcg.com/products/f-td2/](https://ws-tcg.com/products/f-td2/)

**Comment by kwadkore** [comment]
Done. However, I made additional changes and I didn't realize that new commits in my branch would be automatically added to this pull request. I've created a separate branch and pull request for just the one commit (https://github.com/Akenaide/wsoffcli/pull/35) so I'll close this one to avoid having multiple changes in the same pull request.

**Pull request closed without merging**
